// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVA5F4CI5v1iAP_yo2QFaYy4gnWlfHnA',
    appId: '1:65253535734:web:79f8b6841869d4c2c121d7',
    messagingSenderId: '65253535734',
    projectId: 'lyfewearables-app',
    authDomain: 'lyfewearables-app.firebaseapp.com',
    storageBucket: 'lyfewearables-app.firebasestorage.app',
    measurementId: 'G-P7PTTKZKFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDGBtHCjCo3gdAzEzyr-MwjxDIkmzflOc',
    appId: '1:65253535734:android:6ba270fc7a8d648cc121d7',
    messagingSenderId: '65253535734',
    projectId: 'lyfewearables-app',
    storageBucket: 'lyfewearables-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8F4QQ_pIgvBf7WtaouNPQyzonvXnZ2w',
    appId: '1:65253535734:ios:30ecfc7b6ffdaaf7c121d7',
    messagingSenderId: '65253535734',
    projectId: 'lyfewearables-app',
    storageBucket: 'lyfewearables-app.firebasestorage.app',
    iosBundleId: 'com.example.lyfeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8F4QQ_pIgvBf7WtaouNPQyzonvXnZ2w',
    appId: '1:65253535734:ios:30ecfc7b6ffdaaf7c121d7',
    messagingSenderId: '65253535734',
    projectId: 'lyfewearables-app',
    storageBucket: 'lyfewearables-app.firebasestorage.app',
    iosBundleId: 'com.example.lyfeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTVA5F4CI5v1iAP_yo2QFaYy4gnWlfHnA',
    appId: '1:65253535734:web:880f087e4e297891c121d7',
    messagingSenderId: '65253535734',
    projectId: 'lyfewearables-app',
    authDomain: 'lyfewearables-app.firebaseapp.com',
    storageBucket: 'lyfewearables-app.firebasestorage.app',
    measurementId: 'G-DH6DCDG2W5',
  );
}
